org: peerkatserverless
app: python-serverless
service: python-xls20-serverless

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  region: eu-west-2
  iam:
    role: arn:aws:iam::366877760811:role/lambda-role-peerkat-nft-data-serverless
  runtime: python3.8
  layers:
    - arn:aws:lambda:eu-west-2:770693421928:layer:Klayers-p38-Pillow:5
  architecture: x86_64

package:
  patterns:
    - '!venv/**'
    - '!data/**'
    - '!node_modules/**'
    - '!.flake8'
    - '!.gitignore'
    - '!Makefile'
    - '!*.json'
    - '!example.py'
    - '!README.md'
    - '!pyproject.toml'
    - '!env.example'
    - '!env.local'
    - '!logger.log'

functions:
  nft-data-processor:
    handler: handlers.nft_data_handler
    name: nft-processor-${sls:stage}
    timeout: 900
  asset-extraction-retry:
    handler: handlers.retry
    timeout: 900
    events:
      - eventBridge:
          pattern:
            source:
              - aws.s3
            detail-type:
              - Object Created
            detail:
              bucket:
                name:
                  - peerkat-metadata-cache-failed-logger
              object:
                key:
                  - prefix: 'notfound/'
  fetch-assets:
    handler: handlers.fetch_asset_handler
    events:
      - httpApi:
          path: /{token_id}/{asset}
          method: get

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin
  - serverless-step-functions